import os
import pandas as pd


print("Current Working Directory: ", os.getcwd())


data = [
(1, 1, 'Shelter needed for Alice after domestic violence.'),
(1, 2, 'Food supplies required for Alice.'),
(2, 5, 'Psychological support needed for Bob after intimate partner violence.'),
(2, 3, 'Medical care required for Bob.'),
(3, 4, 'Legal assistance needed for Charlie after bullying.'),
(4, 7, 'Counseling required for Diana after workplace violence.'),
(4, 8, 'Housing support needed for Diana.'),
(5, 6, 'Financial assistance needed for Eve.'),
(5, 9, 'Employment support needed for Eve.'),
(6, 1, 'Shelter needed for Frank after domestic violence.'),
(7, 7, 'Counseling required for Grace after workplace violence.'),
(7, 2, 'Food supplies needed for Grace.'),
(8, 5, 'Psychological support needed for Hank after bullying.'),
(9, 4, 'Legal assistance needed for Ivy after intimate partner violence.'),
(9, 6, 'Financial assistance needed for Ivy.'),
(10, 3, 'Medical care required for Sally after bullying.'),
(11, 8, 'Housing support needed for Kim after workplace violence.'),
(11, 7, 'Counseling required for Kim.'),
(12, 1, 'Shelter needed for Liam after domestic violence.'),
(13, 5, 'Psychological support needed for Mia after intimate partner violence.'),
(13, 9, 'Employment support needed for Mia.'),
(14, 4, 'Legal assistance needed for Noah after bullying.'),
(15, 7, 'Counseling required for Olivia after workplace violence.'),
(16, 5, 'Psychological support needed for Paul after intimate partner violence.'),
(16, 2, 'Food supplies needed for Paul.'),
(17, 4, 'Legal assistance needed for Quinn after bullying.'),
(17, 9, 'Employment support needed for Quinn.'),
(18, 7, 'Counseling required for Rita after workplace violence.'),
(19, 1, 'Shelter needed for Sam after domestic violence.'),
(19, 2, 'Food supplies needed for Sam.'),
(20, 5, 'Psychological support needed for Tina after intimate partner violence.'),
(21, 4, 'Legal assistance needed for Uma after bullying.'),
(22, 7, 'Counseling required for Victoria after domestic violence.'),
(22, 8, 'Housing support needed for Victoria.'),
(23, 5, 'Psychological support needed for Wendy after intimate partner violence.'),
(23, 6, 'Financial assistance needed for Wendy.'),
(24, 3, 'Medical care required for Xander after bullying.'),
(25, 8, 'Housing support needed for Yara after workplace violence.'),
(25, 7, 'Counseling required for Yara.'),
(26, 4, 'Legal assistance needed for Zack after intimate partner violence.'),
(26, 9, 'Employment support needed for Zack.'),
(27, 1, 'Shelter needed for Amy after domestic violence.'),
(27, 2, 'Food supplies needed for Amy.'),
(28, 5, 'Psychological support needed for Tracy after bullying.'),
(29, 4, 'Legal assistance needed for Clara after intimate partner violence.'),
(29, 6, 'Financial assistance needed for Clara.'),
(30, 7, 'Counseling required for Dave after workplace violence.'),
(30, 8, 'Housing support needed for Dave.'),
(31, 1, 'Shelter needed for Ella after domestic violence.'),
(32, 3, 'Medical care required for Felix after bullying.'),
(33, 4, 'Legal assistance needed for Gina after intimate partner violence.'),
(33, 5, 'Psychological support needed for Gina.'),
(34, 1, 'Shelter needed for Harry after domestic violence.'),
(34, 2, 'Food supplies needed for Harry.'),
(35, 7, 'Counseling required for Isla after workplace violence.'),
(36, 5, 'Psychological support needed for Bethany after intimate partner violence.'),
(37, 3, 'Medical care required for Kara after bullying.'),
(37, 6, 'Financial assistance needed for Kara.'),
(38, 8, 'Housing support needed for Lee after workplace violence.'),
(39, 1, 'Shelter needed for Mona after domestic violence.'),
(40, 4, 'Legal assistance needed for Nina after bullying.'),
(40, 9, 'Employment support needed for Nina.'),
(41, 5, 'Psychological support needed for Omar after intimate partner violence.'),
(42, 1, 'Shelter needed for Pia after domestic violence.'),
(43, 7, 'Counseling required for Rick after workplace violence.'),
(44, 3, 'Medical care required for Sara after bullying.'),
(45, 1, 'Shelter needed for Tom after domestic violence.'),
(46, 8, 'Housing support needed for Ula after workplace violence.'),
(47, 5, 'Psychological support needed for Vera after intimate partner violence.'),
(48, 3, 'Medical care required for Will after bullying.'),
(48, 7, 'Counseling required for Will.'),
(49, 8, 'Housing support needed for Xena after workplace violence.'),
(50, 4, 'Legal assistance needed for Yuri after intimate partner violence.'),
(51, 1, 'Shelter needed for Zara after domestic violence.'),
(52, 5, 'Psychological support needed for Alan after bullying.'),
(52, 6, 'Financial assistance needed for Alan.'),
(53, 7, 'Counseling required for Beth after intimate partner violence.'),
(54, 1, 'Shelter needed for Carl after domestic violence.'),
(55, 3, 'Medical care required for Dora after bullying.'),
(56, 8, 'Housing support needed for Evan after workplace violence.'),
(57, 5, 'Psychological support needed for Fay after intimate partner violence.'),
(58, 1, 'Shelter needed for Glen after domestic violence.'),
(59, 7, 'Counseling required for Hope after bullying.'),
(60, 8, 'Housing support needed for Ian after workplace violence.'),
(61, 5, 'Psychological support needed for Jill after intimate partner violence.'),
(62, 1, 'Shelter needed for Kyle after domestic violence.'),
(63, 3, 'Medical care required for Lana after bullying.'),
(64, 8, 'Housing support needed for Mark after workplace violence.'),
(65, 4, 'Legal assistance needed for Nora after intimate partner violence.'),
(66, 1, 'Shelter needed for Owen after domestic violence.'),
(67, 5, 'Psychological support needed for Pam after bullying.'),
(68, 8, 'Housing support needed for Quinn after workplace violence.'),
(69, 4, 'Legal assistance needed for Ruth after intimate partner violence.'),
(70, 1, 'Shelter needed for Steve after domestic violence.'),
(71, 3, 'Medical care required for Tara after bullying.'),
(72, 8, 'Housing support needed for Uri after workplace violence.'),
(73, 5, 'Psychological support needed for Vicky after intimate partner violence.'),
(74, 1, 'Shelter needed for Walt after domestic violence.'),
(75, 7, 'Counseling required for Xia after bullying.'),
(76, 8, 'Housing support needed for Yvonne after workplace violence.'),
(77, 4, 'Legal assistance needed for Zane after intimate partner violence.'),
(78, 1, 'Shelter needed for Anna after domestic violence.'),
(79, 3, 'Medical care required for Blake after bullying.'),
(80, 8, 'Housing support needed for Cora after workplace violence.'),
(81, 5, 'Psychological support needed for Dean after intimate partner violence.'),
(82, 1, 'Shelter needed for Ella after domestic violence.'),
(83, 3, 'Medical care required for Finn after bullying.'),
(84, 8, 'Housing support needed for Gail after workplace violence.'),
(85, 5, 'Psychological support needed for Hank after intimate partner violence.'),
(86, 1, 'Shelter needed for Ivy after domestic violence.'),
(87, 7, 'Counseling required for Jade after bullying.'),
(88, 8, 'Housing support needed for Kara after workplace violence.'),
(89, 4, 'Legal assistance needed for Mona after intimate partner violence.'),
(90, 1, 'Shelter needed for Nina after domestic violence.'),
(91, 3, 'Medical care required for Oasis after bullying.'),
(92, 8, 'Housing support needed for Pia after workplace violence.'),
(93, 5, 'Psychological support needed for Quinn after intimate partner violence.'),
(94, 1, 'Shelter needed for Rita after domestic violence.'),
(95, 7, 'Counseling required for Taylor after bullying.'),
(96, 8, 'Housing support needed for Lia after workplace violence.'),
(97, 4, 'Legal assistance needed for Felix after intimate partner violence.'),
(98, 1, 'Shelter needed for Loha after domestic violence.'),
(99, 7, 'Counseling required for Belle after bullying.'),
(100, 8, 'Housing support needed for Tina after workplace violence.'),
(1, 3, 'Medical care required for Alice after domestic violence.'),
(2, 6, 'Financial assistance needed for Bob after intimate partner violence.'),
(3, 7, 'Counseling required for Charlie after bullying.'),
(4, 8, 'Housing support needed for Diana after workplace violence.'),
(5, 1, 'Shelter needed for Eve after intimate partner violence.'),
(6, 2, 'Food supplies required for Frank after domestic violence.'),
(7, 3, 'Medical care required for Grace after workplace violence.'),
(8, 4, 'Legal assistance needed for Hank after bullying.'),
(9, 5, 'Psychological support needed for Ivy after intimate partner violence.'),
(10, 6, 'Financial assistance needed for Sally after bullying.'),
(11, 7, 'Counseling required for Kim after workplace violence.'),
(12, 8, 'Housing support needed for Liam after domestic violence.'),
(13, 1, 'Shelter needed for Mia after intimate partner violence.'),
(14, 2, 'Food supplies required for Noah after bullying.'),
(15, 3, 'Medical care required for Olivia after workplace violence.'),
(16, 4, 'Legal assistance needed for Paul after intimate partner violence.'),
(17, 5, 'Psychological support needed for Quinn after bullying.'),
(18, 6, 'Financial assistance needed for Rita after workplace violence.'),
(19, 7, 'Counseling required for Sam after domestic violence.'),
(20, 8, 'Housing support needed for Tina after intimate partner violence.'),
(21, 1, 'Shelter needed for Uma after bullying.'),
(22, 2, 'Food supplies required for Victoria after domestic violence.'),
(23, 3, 'Medical care required for Wendy after intimate partner violence.'),
(24, 4, 'Legal assistance needed for Xander after bullying.'),
(25, 5, 'Psychological support needed for Yara after workplace violence.'),
(26, 6, 'Financial assistance needed for Zack after intimate partner violence.'),
(27, 7, 'Counseling required for Amy after domestic violence.'),
(28, 8, 'Housing support needed for Tracy after bullying.'),
(29, 1, 'Shelter needed for Clara after intimate partner violence.'),
(30, 2, 'Food supplies required for Dave after workplace violence.'),
(31, 3, 'Medical care required for Ella after domestic violence.'),
(32, 4, 'Legal assistance needed for Felix after bullying.'),
(33, 5, 'Psychological support needed for Gina after intimate partner violence.'),
(34, 6, 'Financial assistance needed for Harry after domestic violence.'),
(35, 7, 'Counseling required for Isla after workplace violence.'),
(36, 8, 'Housing support needed for Bethany after intimate partner violence.'),
(37, 1, 'Shelter needed for Kara after bullying.'),
(38, 2, 'Food supplies required for Lee after workplace violence.'),
(39, 3, 'Medical care required for Mona after domestic violence.'),
(40, 4, 'Legal assistance needed for Nina after bullying.'),
(41, 5, 'Psychological support needed for Omar after intimate partner violence.'),
(42, 6, 'Financial assistance needed for Pia after domestic violence.'),
(43, 7, 'Counseling required for Rick after workplace violence.'),
(44, 8, 'Housing support needed for Sara after bullying.'),
(45, 1, 'Shelter needed for Tom after intimate partner violence.'),
(46, 2, 'Food supplies required for Ula after workplace violence.'),
(47, 3, 'Medical care required for Vera after domestic violence.'),
(48, 4, 'Legal assistance needed for Will after bullying.'),
(49, 5, 'Psychological support needed for Xena after workplace violence.'),
(50, 6, 'Financial assistance needed for Yuri after intimate partner violence.'),
(12, 7, 'Counseling required for Liam after domestic violence.'),
(27, 5, 'Psychological support needed for Amy after domestic violence.'),
(38, 8, 'Housing support needed for Lee after workplace violence.'),
(29, 4, 'Legal assistance needed for Clara after intimate partner violence.'),
(45, 6, 'Financial assistance needed for Tom after domestic violence.'),
(67, 3, 'Medical care required for Pam after bullying.'),
(56, 5, 'Psychological support needed for Evan after workplace violence.'),
(77, 7, 'Counseling required for Zane after intimate partner violence.'),
(48, 2, 'Food supplies needed for Will after bullying.'),
(33, 1, 'Shelter needed for Gina after intimate partner violence.'),
(92, 8, 'Housing support needed for Pia after workplace violence.'),
(15, 4, 'Legal assistance needed for Olivia after workplace violence.'),
(52, 6, 'Financial assistance needed for Alan after bullying.'),
(6, 3, 'Medical care required for Frank after domestic violence.'),
(90, 5, 'Psychological support needed for Nina after domestic violence.'),
(99, 7, 'Counseling required for Belle after bullying.'),
(74, 2, 'Food supplies needed for Walt after domestic violence.'),
(81, 4, 'Legal assistance needed for Dean after intimate partner violence.'),
(59, 1, 'Shelter needed for Hope after bullying.'),
(88, 3, 'Medical care required for Kara after workplace violence.'),
(66, 5, 'Psychological support needed for Owen after domestic violence.'),
(18, 8, 'Housing support needed for Rita after workplace violence.'),
(23, 6, 'Financial assistance needed for Wendy after intimate partner violence.'),
(41, 3, 'Medical care required for Omar after intimate partner violence.'),
(78, 4, 'Legal assistance needed for Anna after domestic violence.'),
(32, 2, 'Food supplies needed for Felix after bullying.')

]


df = pd.DataFrame(data, columns=['incident_id', 'need_id', 'need_description'])


output_path = '/Users/william/Desktop/24 Summer/CS 5200/output.xlsx'

try:
    df.to_excel(output_path, index=False)
    print(f"数据已导出 {output_path}")
except Exception as e:
    print(f" {e}")
